USE [master]
GO

/****** Object:  Database [AppClassScheduling]    Script Date: 10/22/2021 5:53:53 PM ******/
CREATE DATABASE [AppClassScheduling]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppClassScheduling', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AppClassScheduling.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppClassScheduling_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AppClassScheduling_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppClassScheduling].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AppClassScheduling] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AppClassScheduling] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AppClassScheduling] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AppClassScheduling] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AppClassScheduling] SET ARITHABORT OFF 
GO

ALTER DATABASE [AppClassScheduling] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AppClassScheduling] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AppClassScheduling] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AppClassScheduling] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AppClassScheduling] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AppClassScheduling] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AppClassScheduling] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AppClassScheduling] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AppClassScheduling] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AppClassScheduling] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AppClassScheduling] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AppClassScheduling] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AppClassScheduling] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AppClassScheduling] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AppClassScheduling] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AppClassScheduling] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AppClassScheduling] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AppClassScheduling] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AppClassScheduling] SET  MULTI_USER 
GO

ALTER DATABASE [AppClassScheduling] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AppClassScheduling] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AppClassScheduling] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AppClassScheduling] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AppClassScheduling] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AppClassScheduling] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AppClassScheduling] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AppClassScheduling] SET  READ_WRITE 
GO

